// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroEstudiantes.Infraestructura.Data;

#nullable disable

namespace RegistroEstudiantes.Migrations
{
    [DbContext(typeof(RegistroEstudiantesDbContext))]
    [Migration("20260205011238_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RegistroEstudiantes.Dominio.Entidades.Estudiante", b =>
                {
                    b.Property<int>("EstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstudianteId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstudianteId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("RegistroEstudiantes.Dominio.Entidades.EstudianteMateria", b =>
                {
                    b.Property<int>("EstudianteMateriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstudianteMateriaId"));

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("int");

                    b.HasKey("EstudianteMateriaId");

                    b.HasIndex("MateriaId");

                    b.HasIndex("ProfesorId");

                    b.HasIndex("EstudianteId", "MateriaId", "ProfesorId")
                        .IsUnique();

                    b.ToTable("EstudianteMaterias");
                });

            modelBuilder.Entity("RegistroEstudiantes.Dominio.Entidades.Materia", b =>
                {
                    b.Property<int>("MateriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MateriaId"));

                    b.Property<int>("Creditos")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MateriaId");

                    b.ToTable("Materias");
                });

            modelBuilder.Entity("RegistroEstudiantes.Dominio.Entidades.Profesor", b =>
                {
                    b.Property<int>("ProfesorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfesorId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProfesorId");

                    b.ToTable("Profesores");
                });

            modelBuilder.Entity("RegistroEstudiantes.Dominio.Entidades.ProfesorMateria", b =>
                {
                    b.Property<int>("ProfesorMateriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfesorMateriaId"));

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("int");

                    b.HasKey("ProfesorMateriaId");

                    b.HasIndex("MateriaId");

                    b.HasIndex("ProfesorId", "MateriaId")
                        .IsUnique();

                    b.ToTable("ProfesorMaterias");
                });

            modelBuilder.Entity("RegistroEstudiantes.Dominio.Entidades.EstudianteMateria", b =>
                {
                    b.HasOne("RegistroEstudiantes.Dominio.Entidades.Estudiante", "Estudiante")
                        .WithMany("EstudianteMaterias")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RegistroEstudiantes.Dominio.Entidades.Materia", "Materia")
                        .WithMany("EstudianteMaterias")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegistroEstudiantes.Dominio.Entidades.Profesor", "Profesor")
                        .WithMany("EstudianteMaterias")
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Materia");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("RegistroEstudiantes.Dominio.Entidades.ProfesorMateria", b =>
                {
                    b.HasOne("RegistroEstudiantes.Dominio.Entidades.Materia", "Materia")
                        .WithMany("ProfesorMaterias")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegistroEstudiantes.Dominio.Entidades.Profesor", "Profesor")
                        .WithMany("ProfesorMaterias")
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Materia");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("RegistroEstudiantes.Dominio.Entidades.Estudiante", b =>
                {
                    b.Navigation("EstudianteMaterias");
                });

            modelBuilder.Entity("RegistroEstudiantes.Dominio.Entidades.Materia", b =>
                {
                    b.Navigation("EstudianteMaterias");

                    b.Navigation("ProfesorMaterias");
                });

            modelBuilder.Entity("RegistroEstudiantes.Dominio.Entidades.Profesor", b =>
                {
                    b.Navigation("EstudianteMaterias");

                    b.Navigation("ProfesorMaterias");
                });
#pragma warning restore 612, 618
        }
    }
}
