// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroEstudiantes.Infraestructura.Data;

#nullable disable

namespace RegistroEstudiantes.Migrations
{
    [DbContext(typeof(RegistroEstudiantesDbContext))]
    [Migration("20260205012817_SeedDatosIniciales")]
    partial class SeedDatosIniciales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RegistroEstudiantes.Dominio.Entidades.Estudiante", b =>
                {
                    b.Property<int>("EstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstudianteId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstudianteId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("RegistroEstudiantes.Dominio.Entidades.EstudianteMateria", b =>
                {
                    b.Property<int>("EstudianteMateriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstudianteMateriaId"));

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("int");

                    b.HasKey("EstudianteMateriaId");

                    b.HasIndex("MateriaId");

                    b.HasIndex("ProfesorId");

                    b.HasIndex("EstudianteId", "MateriaId", "ProfesorId")
                        .IsUnique();

                    b.ToTable("EstudianteMaterias");
                });

            modelBuilder.Entity("RegistroEstudiantes.Dominio.Entidades.Materia", b =>
                {
                    b.Property<int>("MateriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MateriaId"));

                    b.Property<int>("Creditos")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MateriaId");

                    b.ToTable("Materias");

                    b.HasData(
                        new
                        {
                            MateriaId = 1,
                            Creditos = 3,
                            Nombre = "Matemáticas"
                        },
                        new
                        {
                            MateriaId = 2,
                            Creditos = 3,
                            Nombre = "Física"
                        },
                        new
                        {
                            MateriaId = 3,
                            Creditos = 3,
                            Nombre = "Química"
                        },
                        new
                        {
                            MateriaId = 4,
                            Creditos = 3,
                            Nombre = "Biología"
                        },
                        new
                        {
                            MateriaId = 5,
                            Creditos = 3,
                            Nombre = "Historia"
                        },
                        new
                        {
                            MateriaId = 6,
                            Creditos = 3,
                            Nombre = "Geografía"
                        },
                        new
                        {
                            MateriaId = 7,
                            Creditos = 3,
                            Nombre = "Programación"
                        },
                        new
                        {
                            MateriaId = 8,
                            Creditos = 3,
                            Nombre = "Bases de Datos"
                        },
                        new
                        {
                            MateriaId = 9,
                            Creditos = 3,
                            Nombre = "Redes"
                        },
                        new
                        {
                            MateriaId = 10,
                            Creditos = 3,
                            Nombre = "Ingeniería de Software"
                        });
                });

            modelBuilder.Entity("RegistroEstudiantes.Dominio.Entidades.Profesor", b =>
                {
                    b.Property<int>("ProfesorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfesorId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProfesorId");

                    b.ToTable("Profesores");

                    b.HasData(
                        new
                        {
                            ProfesorId = 1,
                            Nombre = "Profesor A"
                        },
                        new
                        {
                            ProfesorId = 2,
                            Nombre = "Profesor B"
                        },
                        new
                        {
                            ProfesorId = 3,
                            Nombre = "Profesor C"
                        },
                        new
                        {
                            ProfesorId = 4,
                            Nombre = "Profesor D"
                        },
                        new
                        {
                            ProfesorId = 5,
                            Nombre = "Profesor E"
                        });
                });

            modelBuilder.Entity("RegistroEstudiantes.Dominio.Entidades.ProfesorMateria", b =>
                {
                    b.Property<int>("ProfesorMateriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfesorMateriaId"));

                    b.Property<int>("MateriaId")
                        .HasColumnType("int");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("int");

                    b.HasKey("ProfesorMateriaId");

                    b.HasIndex("MateriaId");

                    b.HasIndex("ProfesorId", "MateriaId")
                        .IsUnique();

                    b.ToTable("ProfesorMaterias");

                    b.HasData(
                        new
                        {
                            ProfesorMateriaId = 1,
                            MateriaId = 1,
                            ProfesorId = 1
                        },
                        new
                        {
                            ProfesorMateriaId = 2,
                            MateriaId = 2,
                            ProfesorId = 1
                        },
                        new
                        {
                            ProfesorMateriaId = 3,
                            MateriaId = 3,
                            ProfesorId = 2
                        },
                        new
                        {
                            ProfesorMateriaId = 4,
                            MateriaId = 4,
                            ProfesorId = 2
                        },
                        new
                        {
                            ProfesorMateriaId = 5,
                            MateriaId = 5,
                            ProfesorId = 3
                        },
                        new
                        {
                            ProfesorMateriaId = 6,
                            MateriaId = 6,
                            ProfesorId = 3
                        },
                        new
                        {
                            ProfesorMateriaId = 7,
                            MateriaId = 7,
                            ProfesorId = 4
                        },
                        new
                        {
                            ProfesorMateriaId = 8,
                            MateriaId = 8,
                            ProfesorId = 4
                        },
                        new
                        {
                            ProfesorMateriaId = 9,
                            MateriaId = 9,
                            ProfesorId = 5
                        },
                        new
                        {
                            ProfesorMateriaId = 10,
                            MateriaId = 10,
                            ProfesorId = 5
                        });
                });

            modelBuilder.Entity("RegistroEstudiantes.Dominio.Entidades.EstudianteMateria", b =>
                {
                    b.HasOne("RegistroEstudiantes.Dominio.Entidades.Estudiante", "Estudiante")
                        .WithMany("EstudianteMaterias")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RegistroEstudiantes.Dominio.Entidades.Materia", "Materia")
                        .WithMany("EstudianteMaterias")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegistroEstudiantes.Dominio.Entidades.Profesor", "Profesor")
                        .WithMany("EstudianteMaterias")
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Materia");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("RegistroEstudiantes.Dominio.Entidades.ProfesorMateria", b =>
                {
                    b.HasOne("RegistroEstudiantes.Dominio.Entidades.Materia", "Materia")
                        .WithMany("ProfesorMaterias")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegistroEstudiantes.Dominio.Entidades.Profesor", "Profesor")
                        .WithMany("ProfesorMaterias")
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Materia");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("RegistroEstudiantes.Dominio.Entidades.Estudiante", b =>
                {
                    b.Navigation("EstudianteMaterias");
                });

            modelBuilder.Entity("RegistroEstudiantes.Dominio.Entidades.Materia", b =>
                {
                    b.Navigation("EstudianteMaterias");

                    b.Navigation("ProfesorMaterias");
                });

            modelBuilder.Entity("RegistroEstudiantes.Dominio.Entidades.Profesor", b =>
                {
                    b.Navigation("EstudianteMaterias");

                    b.Navigation("ProfesorMaterias");
                });
#pragma warning restore 612, 618
        }
    }
}
